dist: trusty
sudo: false

language: php
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql
  - postgresql

env:
  global:
    - BRANCH=stable19
    - DB=mysql
    - LINT=false

matrix:
  include:
    - php: 7.2
      env: DB=sqlite
    - php: 7.3
      env: DB=sqlite
    - php: 7.4
      env: DB=sqlite LINT=true
    - env: DB=pgsql
    - env: BRANCH=stable17
    - env: BRANCH=stable18
    - env: BRANCH=master
  allow_failures:
    - env: BRANCH=master


install:
 - which mysql && until mysql -u root -e "show status" &>/dev/null; do sleep 1; done
 - ./tests/travis/install-nc.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=unit-coverage.xml
  - ./vendor/bin/phpunit -c phpunit.integration.xml --coverage-clover=integration-coverage.xml
  - cat ../../data/nextcloud.log
  - if [[ "$LINT" = 'true' ]]; then vendor/bin/php-cs-fixer fix --dry-run; fi
  - rm -rf vendor/ && ../../occ app:check-code ojsxc || true

after_success:
  - bash <(curl -s https://codecov.io/bash)
